version: "3.7"
services:
    app:
        container_name: indigo-app
        build: ./images/php
        ports:
            - "6001:6001"
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - indigo
        depends_on:
            - db

    db:
        image: postgres:15.2
        container_name: indigo-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            SERVICE_TAGS: dev
            SERVICE_NAME: postgres
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
        networks:
            - indigo

    nginx:
        image: nginx:alpine
        container_name: indigo-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - indigo
        depends_on:
            - app

networks:
    indigo:
        driver: bridge
